### ISSUE TITLE
Should `NOOP` in the form of ArrowFunctionExpression be better than FunctionDeclaration?

### ISSUE THREAD

**Issue by LoTwT** [varletjs/rattail#28]
## description

`NOOP` in rattail is using FunctionDeclaration. But I find the same `NOOP` in [Vue](https://github.com/vuejs/core/blob/b5ff930089985a58c3553977ef999cec2a6708a4/packages/shared/src/general.ts#L8) and [Vueuse](https://github.com/vueuse/vueuse/blob/0f11df11962f5f2e912d66c8544bc6767630780a/packages/shared/utils/is.ts#L16) is using ArrowFunctionExpression. So should `NOOP` in the form of ArrowFunctionExpression be better than FunctionDeclaration?

**Comment by haoziqaq** [comment]
There is no difference between ArrowFunctionExpression and FunctionDeclaration. In order to unify the code style and reduce the scope problem of arrow functions, FunctionDeclaration is used here.

**Comment by LoTwT** [comment]
Thank you for your explanation. ♥️
