### ISSUE TITLE
What about adding unified type helpers and making params more semantic?

### ISSUE THREAD

**Issue by LoTwT** [varletjs/rattail#31]
## description

When I explore codes, I find that there're similar type helpers `type Fn<T> = (a: T, b: T) => any` or inline types in the `differenceWith`, `intersectionWith`, and `uniqBy`.

They're `predicate` that should return `Truthy` or `Falsy`. So what about letting the return type be `boolean`?

The name `Fn` is not semantic, what about `Predicate`, `CallbackFn`, `CompareFn`, or some others? At the same time, the param name of the function declaration could be the lowercase string corresponding to the type name, like `function differenceWith<T>(arr: T[], ...values: [...T[][], predicate: Predicate<T>]): T[]`

PS. I find there are both generic array types `Array<T>` and `T[ ]` in the codes. Should they be in the same form by the code style? 🤣

**Comment by haoziqaq** [comment]
Q1: They're predicate that should return Truthy or Falsy. So what about letting the return type be boolean?
- A: `Truthy` or `Falsy` are not strictly equals to `boolean`. Refer to `Array.prototype.filter`. It may be better to return type `any` or `unknown`.

Q2: The name Fn is not semantic, what about Predicate, CallbackFn, CompareFn, or some others? At the same time, the param name of the function declaration could be the lowercase string corresponding to the type name, like function differenceWith<T>(arr: T[], ...values: [...T[][], predicate: Predicate<T>]): T[]
Q3: I find there are both generic array types Array<T> and T[ ] in the codes. Should they be in the same form by the code style? 
- A: Yes, these are all optimization points that need to be optimized before exposing these types to users.
