### ISSUE TITLE
migrate to use vitest browser mode than vitest + jsdom

### ISSUE THREAD

**Issue by LoTwT** [varletjs/rattail#34]
## description

When I try to improve some test suits, I find that there will be issues with the test environment.

For example, when testing `getScrollTop(window)`, `"scrollTop" in element` will be `true` 😧, I'm not sure if this is related to the `jsdom`. But this will affect the test suites.

I think it may be better to try [vitest browser mode](https://vitest.dev/guide/browser/), although it's an experimental feature. Some of the utils are browser-related, so we could try to add a [workspace](https://vitest.dev/guide/workspace.html) to test them isolatedly.

**Comment by haoziqaq** [comment]
`Vitest Browser Mode` seems to be more suitable for application-level e2e testing. For libraries like `rattail`, I think `jsdom` is enough.

**Comment by haoziqaq** [comment]
By the way, if there is a need to migrate `vitest browser mode` in the future, `varlet ui` and `rattail` may be migrated together.

**Comment by LoTwT** [comment]
Some utils are browser-related and use browser APIs. They could be tested better in a real browser environment. The behaviors of these utils are user-designed, so they need e2e tests.

I think dividing them into a separate workspace and testing them are better. But it requires more effort but rewards less... 😢
